name: emobility
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Custom dependencies
  flutter_staggered_animations: ^1.0.0
  confetti: ^0.7.0
  page_view_dot_indicator: ^2.3.0
  flutter_swipable: ^1.1.0
  carousel_slider: ^4.2.1
  google_nav_bar: ^5.0.6
  restart_app: ^1.2.1
  datetime_picker_formfield: ^2.0.0
  lottie: ^2.3.0
  intl: ^0.17.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  hidden_drawer_menu: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/images/christ_logo.jpg
    - lib/images/accounts.png
    - lib/images/confetti.json
    - lib/images/icon_android.jpg

    # equipments images added below
    - lib/images/equipments/cellsForTesting.jpg
    - lib/images/equipments/environmentalChamber.jpg
    - lib/images/equipments/fixtureForCellTesting.png
    - lib/images/equipments/impedanceAnalyzer.png
    - lib/images/equipments/liIonPackTestingChrgDischrg.jpg
    - lib/images/equipments/liIonTest.png
    - lib/images/equipments/multiCellBMS.jpg
    - lib/images/equipments/PackACIRTestingLab.jpg
    - lib/images/equipments/singleCellBMS.png
    - lib/images/equipments/wiring&FixtureTesting.png
    - lib/images/equipments/bmsAlgSoftwares.jpg

    # faculty board images added below
    - lib/images/facultyBoardImages/fr_shijen.jpg
    - lib/images/facultyBoardImages/fr_soni_j_c.jpg
    - lib/images/facultyBoardImages/haneesh_k_m.jpg
    - lib/images/facultyBoardImages/Harish_Kumar.jpg
    - lib/images/facultyBoardImages/joseph_x_rodrigues.jpg
    - lib/images/facultyBoardImages/mari_anita.jpg
    - lib/images/facultyBoardImages/parag_jose.jpeg
    - lib/images/facultyBoardImages/pragashK.jpg
    - lib/images/facultyBoardImages/raghunandan_kumar.jpeg
    - lib/images/facultyBoardImages/venkataswamy_r.jpeg

  fonts:
    - family: playWrite
      fonts:
        - asset: lib/fonts/Playwrite_België_Vlaams_Gewest/PlaywriteBEVLG-VariableFont_wght.ttf
    - family: timesRoman
      fonts:
        - asset: lib/fonts/times_new_roman/times_new_roman.ttf
    - family: IBMPlexSans
      fonts:
        - asset: lib/fonts/IBM_plexSans/IBMPlexSans-MediumItalic.ttf
    - family: IBMPlexSansBold
      fonts:
        - asset: lib/fonts/IBM_plexSans/IBMPlexSans-SemiBold.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: lib/fonts/Playfair_Display/static/PlayfairDisplay-Regular.ttf
        - asset: lib/fonts/Playfair_Display/static/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Lora
      fonts:
        - asset: lib/fonts/Lora,Playfair_Display/Lora/static/Lora-Regular.ttf
        - asset: lib/fonts/Lora,Playfair_Display/Lora/static/Lora-Bold.ttf
          weight: 700
